services:
  - type: web
    name: cv-cover-letter-builder
    env: python
    buildCommand: 'pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput'
    startCommand: 'gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 2 --threads 2 --timeout 60 --log-level debug --error-logfile -'
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: 'cv-cover-letter-builder.onrender.com,localhost,127.0.0.1,*.onrender.com'
      - key: DJANGO_SETTINGS_MODULE
        value: 'core.settings'
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: cv-cover-letter-builder-db
          property: connectionString

databases:
  - name: cv-cover-letter-builder-db
    databaseName: cv_cover_letter_builder
    user: cv_user
    plan: free
    region: frankfurt # or choose your nearest region
    ipAllowList: [] # only allow internal connections
