services:
  - type: web
    name: cv-cover-letter-builder
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python scripts/manage.py migrate && python scripts/manage.py collectstatic --noinput && gunicorn core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: "*"
