# Generated by Django 4.2.23 on 2025-08-11 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('template_content', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('preview_image', models.ImageField(blank=True, help_text='Preview image for the template', null=True, upload_to='template_previews/')),
                ('type', models.CharField(choices=[('cv', 'CV Template'), ('cover_letter', 'Cover Letter Template')], default='cv', max_length=20)),
                ('style', models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('creative', 'Creative'), ('minimal', 'Minimal'), ('basic', 'Basic')], default='modern', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedCV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploaded_cvs/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CVSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.cv')),
            ],
        ),
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0)),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=dict)),
                ('experience_level', models.CharField(default='Entry Level', max_length=50)),
                ('ats_compatibility', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.uploadedcv')),
            ],
        ),
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField(default='')),
                ('generated_letter', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.cv')),
            ],
        ),
        migrations.CreateModel(
            name='AICoverLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('generated_letter', models.TextField()),
                ('cv_analysis', models.TextField(blank=True)),
                ('template_type', models.CharField(default='standard', max_length=50)),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('creative', 'Creative'), ('formal', 'Formal'), ('casual', 'Casual')], default='professional', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.uploadedcv')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
