# Generated by Django 5.2.5 on 2025-08-12 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='preview_image',
            field=models.ImageField(
                upload_to='template_previews/',
                null=True,
                blank=True,
                help_text='Preview image for the template'
            ),
        ),
    ]
