# Generated by Django 5.2.4 on 2025-07-17 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_add_created_at_fields'),
    ]

    operations = [
    ]
