# Generated by Django 5.2.5 on 2025-08-14 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20250812_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='style',
            field=models.CharField(
                choices=[
                    ('modern', 'Modern'),
                    ('classic', 'Classic'),
                    ('creative', 'Creative'),
                    ('minimal', 'Minimal'),
                    ('professional', 'Professional')
                ],
                default='modern',
                max_length=20
            ),
        ),
        migrations.AddField(
            model_name='template',
            name='type',
            field=models.CharField(
                choices=[
                    ('cv', 'CV'),
                    ('resume', 'Resume'),
                    ('cover_letter', 'Cover Letter'),
                    ('portfolio', 'Portfolio')
                ],
                default='cv',
                max_length=20
            ),
        ),
    ]
