# Generated by Django 5.2.5 on 2025-08-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20250814_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='style',
            field=models.CharField(choices=[('modern', 'Modern'), ('classic', 'Classic'), ('creative', 'Creative'), ('minimal', 'Minimal'), ('basic', 'Basic')], default='modern', max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='type',
            field=models.CharField(choices=[('cv', 'CV Template'), ('cover_letter', 'Cover Letter Template')], default='cv', max_length=20),
        ),
    ]
