# Generated by Django 5.2.4 on 2025-07-17 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_add_created_at_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coverletter',
            name='letter_text',
        ),
        migrations.RemoveField(
            model_name='cvsection',
            name='heading',
        ),
        migrations.AddField(
            model_name='coverletter',
            name='generated_letter',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='coverletter',
            name='job_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cvsection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='coverletter',
            name='job_title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cv',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='cvsection',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.cv'),
        ),
    ]
