# Generated by Django 5.2.4 on 2025-07-18 22:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_remove_coverletter_letter_text_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('template_content', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedCV',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='uploaded_cvs/')),
                ('original_filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CVAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.IntegerField(default=0)),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('keywords', models.JSONField(default=dict)),
                ('experience_level', models.CharField(default='Entry Level', max_length=50)),
                ('ats_compatibility', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_cv', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='builder.uploadedcv')),
            ],
        ),
        migrations.CreateModel(
            name='AICoverLetter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('generated_letter', models.TextField()),
                ('tone', models.CharField(choices=[('professional', 'Professional'), ('creative', 'Creative'), ('formal', 'Formal'), ('casual', 'Casual')], default='professional', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builder.uploadedcv')),
            ],
        ),
    ]
