# Generated by Django 4.2.23 on 2025-07-20 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('builder', '0005_template_uploadedcv_cvanalysis_aicoverletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='aicoverletter',
            name='cv_analysis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aicoverletter',
            name='template_type',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='aicoverletter',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aicoverletter',
            name='uploaded_cv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.uploadedcv'),
        ),
    ]
